---
version: 2

defaults: &defaults
  docker:
    - image: circleci/ruby:2.5.1-node-browsers-legacy
  working_directory: ~/circleci-eks-agent
  environment:
    LIBRARY: joatmon08
    CONTAINER_NAME: circleci-eks-agent

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the runner
          command: docker build -t $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1 .
      - run:
          name: Push the image to Docker Hub
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push $LIBRARY/$CONTAINER_NAME:$CIRCLE_BUILD_NUM-$CIRCLE_SHA1
      - run:
          name: store image version
          command: |
            mkdir /tmp/build
            echo "IMAGE_VERSION=$CIRCLE_BUILD_NUM-$CIRCLE_SHA1" > /tmp/build/version.env
      - persist_to_workspace:
          name: persist version across jobs
          root: /tmp/build
          paths:
            - version.env
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: configuration tests
          command: |
            source /tmp/workspace/version.env
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            docker pull $LIBRARY/$CONTAINER_NAME:$IMAGE_VERSION
            CID=$(docker run -d -v /var/run/docker.sock:/var/run/docker.sock:ro $LIBRARY/$CONTAINER_NAME:$IMAGE_VERSION sleep 360)
            inspec exec profiles/circleci_eks_agent -t docker://$CID
            touch /tmp/build/cid.env
            echo "CID=$CID" > /tmp/build/cid.env
      - run:
          name: cleanup
          when: always
          command: |
            source /tmp/build/cid.env
            docker rm -f $CID

workflows:
  version: 2
  circleci-eks-agent:
    jobs:
      - build
      - test:
          requires:
            - build